### ISSUE TITLE
Type checker does not apply negative isinstance narrowing in else/elif branches

### ISSUE THREAD

**Issue by kugesan1105** [jaseci-labs/jaseci#8330]
## Summary

The type checker applies positive `isinstance` narrowing but never applies the negation: in the `else`/`elif` of an `isinstance(x, T)` check, `T` is not subtracted from the union, so runtime-safe code fails `jac check` with a false positive. mypy and pyright both perform this subtraction.

This is what broke `jac-check` on main after #8316 landed (`graph_query.impl.jac`, E1099). #8329 works around it at that call site, but the underlying narrowing gap remains.

## Minimal reproduction

```jac
def f(x: (type | tuple | None)) -> str {
    if isinstance(x, tuple) {
        return "tuple";
    } elif x is not None {
        return x.__name__;
    }
    return "*";
}

with entry {
    print(f(str), f((str, int)), f(None));
}
```

`jac check repro.jac`:

```
error[E1099]: Cannot access attribute "__name__" for type "type | tuple"; attribute is missing from tuple
  --> repro.jac:5:18
    5 |         return x.__name__;
      |                  ^^^^^^^^
```

`jac run repro.jac` executes fine and prints `str tuple *`.

## Expected

In the `elif` branch the checker should compute `(type | tuple | None) - tuple = type | None`, then the `x is not None` guard leaves `type`, and `x.__name__` resolves via typeshed (`type.__name__: str`).

## Actual

The `elif` branch keeps `x` as `type | tuple` (only the `is not None` guard narrowed), and attribute access on the union fails because `tuple` lacks `__name__`.

## Notes

- Positive narrowing works: inside `if isinstance(x, tuple)` the checker correctly narrows `x` to `tuple`, and `elif isinstance(x, type)` narrows to `type` (the workaround used in #8329).
- Attribute resolution itself is healthy: with the parameter typed as plain `type`, `x.__name__` checks clean, so the gap is purely in flow narrowing.
- Related: #8288, #8316.

**Comment by kugesan1105** [comment]
Validated, the root cause is narrower than described: negative isinstance narrowing works in general (`str | int` minus `int`, `str | list` minus `list`, and the exact repro with `list` in place of `tuple` all pass). The bug is that `isinstance(x, tuple)` performs no narrowing at all, positive or negative.

`_isinstance_tuple_alternatives` (type_evaluator.impl.jac:5051) detects the `isinstance(x, klasses)` tuple-of-classes form solely via `arg_type.shared == prefetch.tuple_class.shared`. The bare class `tuple` shares that `shared`, so it is misread as a tuple-of-classes value; its empty `type_args` yield `alts = []`, which `_extract_isinstance_info` turns into `return None`: no `NarrowingPredicate` is built for the condition.

Proof: `isinstance(x, (tuple,))` (literal `TupleVal` path) and `isinstance(x, MyT)` with `class MyT(tuple)` both narrow correctly. Positive narrowing is also dead, inside `if isinstance(x, tuple)` a bogus attribute access on `x: str | tuple` still reports `str | tuple`, so the "positive narrowing works" note above is inaccurate.

Fix: require `arg_type.is_instance()` in `_isinstance_tuple_alternatives` so the bare class falls through to `_convert_to_instance(arg_type)`.
