### ISSUE TITLE
Type checker: singleton pattern on module globals reports "X | NoneType, expected X" in batch checks

### ISSUE THREAD

**Issue by marsninja** [jaseci-labs/jaseci#7165]
## Symptom

The standard lazy-singleton pattern on a module global is rejected — but only when the file is checked as part of a multi-file batch (as CI does), not standalone:

```jac
obj Foo {}

glob _inst: (Foo | None) = None;

def get_foo -> Foo {
    global _inst;
    if _inst is None {
        _inst = Foo();
    }
    return _inst;
}
```

Real site: `jac/jaclang/cli/impl/console.impl.jac:707`

```
✖ Error: error[E1002]: Cannot return JacConsole | NoneType, expected JacConsole
  --> jac/jaclang/cli/impl/console.impl.jac:707:12
  707 |     return _console_instance;
```

`_console_instance` is narrowed by `if _console_instance is None { _console_instance = Jac.get_console(); }` immediately above, so the union should be resolved to `JacConsole` on the return.

## Root cause

The minimal pattern above **passes** when checked standalone, as do variants with decl/impl split, `import type` aliases, and intervening imports — narrowing of globals works in isolation. The failure appears only in shared-`JacProgram` batch runs (320-file sweep, and any CI run), which points to the batch type-identity split (#7164): `Jac.get_console()` returns `JacConsole` via `import type from jaclang.cli.console { JacConsole as ConsoleImpl }`; when the batch has created a second declaration instance of `JacConsole`, the assignment no longer matches the declared type, the narrow does not apply, and the checker falls back to the declared union.

Filed separately from #7164 because the narrowing path deserves its own regression coverage: even with duplicated declarations, assignment-based narrowing failing *silently* (falling back to the declared type rather than erroring at the assignment) is what turns an identity bug into a confusing diagnostic two statements later.

## Proper fix

- Primary: fix declaration identity in batch checks (#7164).
- In the narrowing engine: when an assignment narrows a global, record the narrow keyed on the symbol, and if the assigned type fails to unify with the declared type, surface the mismatch **at the assignment site** instead of silently discarding the narrow.
- Regression test: the snippet above must stay green when checked in a batch alongside its module's decl file and an unrelated consumer.

## Impact

144 instances of the `return X | NoneType, expected X` shape across the sweep (audit that produced #7157) — `cli/impl/console.impl.jac`, `cli/impl/executor.impl.jac`, `cli/impl/help.impl.jac`, `cli/impl/registry.impl.jac`, and the same singleton pattern across `runtimelib`.
