### ISSUE TITLE
native/checker: struct.unpack destructuring still untypable — needs format-string-aware typing or a gradual-any arithmetic floor

### ISSUE THREAD

**Issue by marsninja** [jaseci-labs/jaseci#7314]
## Summary

Residual case from #7238 (fixed by #7242). The tuple-destructuring machinery itself now works — for-loop destructuring and per-index heterogeneous tuple typing are verified fixed on main @ `42d44f0e7` — but the `struct.unpack` destructuring example from that issue still fails, exactly as scoped out in #7242's commit note:

> The `struct.unpack(...)` destructuring example in the issue additionally requires format-string-aware element typing (it returns `tuple[Any, ...]`); that is a separate `struct`-typing concern.

Filing that separate concern so it's tracked.

## Repro (na)

```jac
import struct;

def hdr(data: bytes) -> int {
    (a, b) = struct.unpack("<ii", data[0:8]);
    return a + b;
    // error[E1055]: No matching overload found for method "__add__"
    // error[E1002]: Cannot return <Unknown>, expected int
}
```

With the #7239 fix in, the module now correctly refuses to run (and `jac check` agrees) — but there is no way to write this idiom at all: the destructured targets come out as the `...` element type and arithmetic on them finds no overload.

## Two possible layers of fix

1. **Format-string-aware `struct.unpack` typing** (the full fix): a literal format string fully determines arity and element types — `"<ii"` → `tuple[int, int]`, `"<56sii"` → `tuple[bytes, int, int]`. CPython's own typeshed can't do this, but jac controls its checker; the format mini-language is small and this is the dominant `struct` usage pattern in binary parsers.
2. **Gradual-`any` arithmetic floor** (the fallback): even without format awareness, destructuring `tuple[Any, ...]` should give `any` targets whose arithmetic boxes through the JacVal pathway rather than failing overload resolution — consistent with the "gradual foreign any" direction (#7156) and adjacent to the open #6803 (`struct.unpack(...)[0]` returned from an impl-annex method fails E1002).

Layer 2 makes the idiom *writable*; layer 1 makes it *well-typed*. Current workaround is indexing with annotated locals:

```jac
header = struct.unpack("<ii", data[0:8]);
a: int = header[0];
b: int = header[1];
```

## Environment

- jac 0.30.5 binary (macOS arm64), jaclang main @ `42d44f0e7` via `[dev] jaclang_source`
- Real-world context: the PAK parser in marsninja/quakepassion#20 (binary-format parsing is where this idiom is unavoidable)

**Comment by marsninja** [comment]
Closing: no activity in 10+ days. Reopen if still relevant.
