### ISSUE TITLE
bug(ecmascript): builtin type as a value compiles to a string, throws "int" is not a function

### ISSUE THREAD

**Issue by udithishanka** [jaseci-labs/jaseci#7454]
## Summary

In the client (ecmascript) backend, a builtin type name (`int`, `str`, `float`, `bool`) used as a **value / first-class callable** is lowered to a bare JS **string literal** (e.g. `"int"`). Any later call on that value throws `TypeError: "int" is not a function` in the browser. This is the **value/reference** case only: `map(int, parts)`, `sorted(items, key=int)`, `f = int; f(x)`, or storing a builtin type in a collection. **Direct calls (`int(x)`) are NOT affected on current main** — they compile correctly to `Math.trunc(Number(x))`.

`jac check` stays silent and the build succeeds, so the failure only appears at runtime in the browser.

Introduced by #6510 (`becd0452f`), which added `exit_builtin_type` to lower builtin-type values to a type-name string so `isinstance` codegen works, but applied it unconditionally, including callable/value positions.

## Scope (please read — avoids conflation)

There are two distinct failure modes with the same `"int" is not a function` message. **This issue is only the first:**

- **(this issue) Value/reference position** — `map(int, …)`, `key=int`, `f = int`. **Still broken on current `dev` (0.32.0).** Fix needed.
- **(NOT this issue) Direct calls** `int(x)` — was broken in an earlier binary window (post-#6510) and is **already fixed on current main** (verified on 0.30.8 and 0.32.0, both emit `Math.trunc(Number(x))`). A stale prebuilt bundle compiled during that window still shows `"int"(...)` for direct calls; the remedy there is a rebuild against a current binary, not a code fix. Do not assume fixing this issue covers that, or vice versa.

## Environment

- `jac --version`: **0.32.0** (`dev` channel, macOS arm64) — value case reproduces
- Also confirmed on **0.30.8** (compiler source at commit `1090c55de`, 2026-07-07)
- Codegen origin commit present: `becd0452f` (#6510)
- Path: `jac/jaclang/compiler/passes/ecmascript/impl/esast_gen_pass.impl.jac`

## Reproduction (executed, not hypothetical)

`repro.cl.jac`:

```jac
def parse_all(parts: list) -> list {
    return list(map(int, parts));   # int used as a value/callback
}

def sort_nums(items: list) -> list {
    return sorted(items, key=int);  # builtin type as a key= function
}

def alias_call(x: str) -> int {
    f = int;                        # aliasing a builtin type
    return f(x);
}

def direct_call(x: str) -> int {
    return int(x);                  # direct call - correct, for contrast
}
```

```bash
jac tool jac2js repro.cl.jac
# exit code: 0  (compiles clean, no error)
```

Emitted JS on `dev` 0.32.0 (the four user functions):

```js
function parse_all(parts) {
  return Array.from(parts.map("int"));      // <-- "int" is a string, not a function
}
function sort_nums(items) {
  return _jac.builtin.sorted(items, "int"); // <-- key is the string "int"
}
function alias_call(x) {
  let f = "int";                            // <-- alias is a string
  return f(x);
}
function direct_call(x) {
  return Math.trunc(Number(x));             // <-- direct call: correct
}
```

Running the emitted `parse_all` in node reproduces the exact browser error:

```bash
node -e 'function parse_all(p){return Array.from(p.map("int"))} try{parse_all(["1","2"])}catch(e){console.log(e.constructor.name+": "+e.message)}'
# TypeError: string "int" is not a function
```

## Expected

Valid Jac that passes a builtin type as a value (a `map`/`filter` callback, a `key=` function, an alias, an element stored in a collection) should compile to a working JS callable. `map(int, parts)` should behave like Python's `list(map(int, parts))`, i.e. coerce each element, not throw.

## Actual

`exit_builtin_type` unconditionally lowers a builtin type used as a value to a string tag:

```jac
# jac/jaclang/compiler/passes/ecmascript/impl/esast_gen_pass.impl.jac
impl EsastGenPass.exit_builtin_type(nd: uni.BuiltinType) -> None {
    type_name = nd.sym_name;
    tag = self.sync_loc(
        es.Literal(value=type_name, raw=json.dumps(type_name)), jac_node=nd
    );
    nd.gen.es_ast = tag;
}
```

That string is correct only in *type* positions (`isinstance(x, int)`, where the runtime compares against `"int"`). In value/callable position it becomes a string that gets called. The builtin-emitter path that would coerce it correctly only fires for direct calls whose callee is a `uni.Name`:

```jac
# esast_gen_pass.impl.jac
if _call_kind == "builtin" and isinstance(nd.target, uni.Name) {
    ...  # emit_int -> Math.trunc(Number(x)), etc.
}
```

A value-position reference to a builtin type never reaches that path, so it degrades to the string literal.

## Impact

- Hits any client-side (`.cl.jac`) program that uses a builtin type as a **value**: `map(int, ...)`, `sorted(..., key=int/str)`, `filter`, aliasing, storing in a list/dict. These are idiomatic Python/Jac patterns, so LLM-generated apps can emit them.
- Silent at compile time (`jac check` green, build succeeds); fails only at runtime in the browser.
- Symptom overlaps with the already-fixed direct-call breakage (both print `"int" is not a function`), which is why this is easy to misattribute. See the Scope section.

## Workaround (verified)

Wrap the builtin-type reference in a lambda so the callee becomes a direct call:

```jac
# instead of: list(map(int, parts))
list(map(lambda x: any -> int { return int(x); }, parts));
```

Verified on 0.32.0: the inner `int(x)` compiles to `Math.trunc(Number(x))` and runs correctly.

## Suggested fix

Branch `exit_builtin_type` (and/or the call/reference handling) on usage:

- **Type position** (isinstance arg, annotation): keep the string tag.
- **Value / callable position** (call argument, RHS of assignment, `key=`, collection element): emit an actual callable, e.g. a reference to the runtime coercion (`_jac.builtin.int`) or a thunk `((x) => Math.trunc(Number(x)))`, reusing the emitters `exit_func_call` already uses for direct calls.

Equivalently, let the builtin-emitter branch also accept `uni.BuiltinType` callees / value-position references and give them a callable lowering.

**Regression test:** add a `test_client_codegen` case asserting `map(int, xs)`, `sorted(xs, key=int)`, and `f = int; f(x)` do not emit a bare `"int"`/`"str"` string in callable position (assert the artifact contains a coercion call, not `.map("int")`). This guards the contract #6510 broke.

Related: #6510 (`becd0452f`, introduced the lowering).
