### PR TITLE
fix(typecheck): narrow lazy singletons initialized from an Any value (#7165)

### LINKED ISSUE #7165: Type checker: singleton pattern on module globals reports "X | NoneType, expected X" in batch checks
## Symptom

The standard lazy-singleton pattern on a module global is rejected — but only when the file is checked as part of a multi-file batch (as CI does), not standalone:

```jac
obj Foo {}

glob _inst: (Foo | None) = None;

def get_foo -> Foo {
    global _inst;
    if _inst is None {
        _inst = Foo();
    }
    return _inst;
}
```

Real site: `jac/jaclang/cli/impl/console.impl.jac:707`

```
✖ Error: error[E1002]: Cannot return JacConsole | NoneType, expected JacConsole
  --> jac/jaclang/cli/impl/console.impl.jac:707:12
  707 |     return _console_instance;
```

`_console_instance` is narrowed by `if _console_instance is None { _console_instance = Jac.get_console(); }` immediately above, so the union should be resolved to `JacConsole` on the return.

## Root cause

The minimal pattern above **passes** when checked standalone, as do variants with decl/impl split, `import type` aliases, and intervening imports — narrowing of globals works in isolation. The failure appears only in shared-`JacProgram` batch runs (320-file sweep, and any CI run), which points to the batch type-identity split (#7164): `Jac.get_console()` returns `JacConsole` via `import type from jaclang.cli.console { JacConsole as ConsoleImpl }`; when the batch has created a second declaration instance of `JacConsole`, the assignment no longer matches the declared type, the narrow does not apply, and the checker falls back to the declared union.

Filed separately from #7164 because the narrowing path deserves its own regression coverage: even with duplicated declarations, assignment-based narrowing failing *silently* (falling back to the declared type rather than erroring at the assignment) is what turns an identity bug into a confusing diagnostic two statements later.

## Proper fix

- Primary: fix declaration identity in batch checks (#7164).
- In the narrowing engine: when an assignment narrows a global, record the narrow keyed on the symbol, and if the assigned type fails to unify with the declared type, surface the mismatch **at the assignment site** instead of silently discarding the narrow.
- Regression test: the snippet above must stay green when checked in a batch alongside its module's decl file and an unrelated consumer.

## Impact

144 instances of the `return X | NoneType, expected X` shape across the sweep (audit that produced #7157) — `cli/impl/console.impl.jac`, `cli/impl/executor.impl.jac`, `cli/impl/help.impl.jac`, `cli/impl/registry.impl.jac`, and the same singleton pattern across `runtimelib`.

### PR DESCRIPTION
**Pull request by marsninja**
## Summary

Fixes #7165. The lazy-singleton idiom guards an optional slot and initializes it once:

```jac
glob _inst: (T | None) = None;
def get -> T {
    global _inst;
    if _inst is None { _inst = init(); }
    return _inst;
}
```

When `init()` has an imprecise `Any` type — `json.loads`, or a call into an installed-but-untyped third-party package that degrades to foreign `Any` (#7161) — the assignment-based narrowing engine **discarded** the narrow and fell back to the declared `T | None`. Two statements later that surfaced as a confusing `Cannot return T | NoneType, expected T` (E1002), the shape audited in #7157 across `cli/impl/*` and `runtimelib`. The concrete-type variant was already resolved by the batch declaration-identity fix (#7164); this closes the remaining `Any`-initializer path.

## Approach

A flat assignment of an imprecise value still writes a concrete, non-`None` value on that path, so `Any` is imprecise — not `None`. In `_get_type_from_flow_node`, when a flat assignment's RHS is an explicit/foreign `Any` and the declared slot is optional, narrow the slot to its non-`None` form (reusing the existing `exclude_type_from_union` primitive) instead of dropping the narrow. A genuinely incompatible **concrete** initializer is untouched and is still surfaced at the assignment site (E1001), so real bugs are not masked.

## Tests

New `test_global_narrowing` (mirrors the #7164 batch harness):

- **explicit-`Any` singleton** checked in a decl + impl-annex + consumer batch — no return-cascade;
- **foreign-`Any`** singleton initialized from an installed untyped third-party call — checks fully clean;
- **control** — an incompatible concrete initializer still errors.

All fail on `main` with the E1002 cascade and pass with the fix. Targeted run of `test_global_narrowing`, `test_batch_decl_identity`, and `test_untyped_third_party` is green.

### CODE REVIEW

File: jac/jaclang/compiler/type_system/type_evaluator.impl/type_evaluator.impl.jac [hunk 1]
```diff
@@ -3785,6 +3785,25 @@ impl TypeEvaluator._get_type_from_flow_node(
                         and not self.assign_type(declared_type, assigned_type)
                     ) {
                         narrowed_from_assignment = assigned_type;
+                    } elif (
+                        flat_target_matched
+                        and self.is_explicit_any(assigned_type)
+                        and self._union_contains_none(declared_type)
+                        and self.prefetch.none_type_class
+                    ) {
```
[the remark this answers is not in the document]
Comment (marsninja) [reply jac/jaclang/compiler/type_system/type_evaluator.impl/type_evaluator.impl.jac:3792]: Good catch on the noise. The check is a runtime no-op given `_union_contains_none`, but it was also doing double duty as the type narrow that lets `none_type_class` (`ClassType | None`) reach `_convert_to_instance(TypeBase)`. Pulled it into a local with an explicit `is not None` narrow so the intent reads as type-narrowing rather than a redundant guard.

File: jac/jaclang/compiler/tests/test_global_narrowing.jac [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+    importlib.invalidate_caches();
+    try {
+        prog = JacProgram();
+        prog.compile(file_path="gn_src.jac", use_str=src, type_check=True);
+        return prog;
+    } finally {
+        sys.path.remove(search_dir);
+        importlib.invalidate_caches();
+    }
+}
```
[the remark this answers is not in the document]
Comment (marsninja) [reply jac/jaclang/compiler/tests/test_global_narrowing.jac:83]: Agreed, applied. Moved the `sys.path.insert`/`invalidate_caches` inside the `try` and guarded the `finally` removal with a membership check so cleanup always mirrors a successful insert.
