### ISSUE TITLE
`auth_redirect` config in file-based routing has never worked

### ISSUE THREAD

**Issue by SahanUday** [jaseci-labs/jaseci#6871]
## Summary

When running an app that uses file-based routing (`pages/` directory), the following warning always appears in the terminal on every build/run:

```
⚠ Failed to load routing config, using default auth_redirect='/login': cannot import name 'PluginConfig' from 'jaclang.runtimelib.client.config_loader'
```

<img width="897" height="100" alt="Image" src="https://github.com/user-attachments/assets/486237a4-6546-45a1-aea5-69f872c30bb2" />

The app still starts and works correctly, but the `auth_redirect` configuration value has never been readable since file-based routing was introduced in PR #4422. There are three stacked bugs in `_create_pages_entry_content()` inside `compiler.impl.jac`.

---

## Affected file

`jac/jaclang/runtimelib/client/impl/compiler.impl.jac` — method `_create_pages_entry_content`, lines ~133–145

```jac
auth_redirect = "/login";
try {
    import from jaclang.runtimelib.client.config_loader { PluginConfig }   # Bug 1
    config = PluginConfig.load(self.project_dir);                           # Bug 2
    if config and config?.routing and config.routing {
        auth_redirect = config.routing.get('auth_redirect', '/login');      # Bug 3
    }
} except Exception as e {
    console.warning(
        f"Failed to load routing config, using default auth_redirect='/login': {e}"
    );
}
```

---

## Bug 1 — Wrong class name: `PluginConfig` does not exist

The import asks for `PluginConfig` but the class in `jaclang.runtimelib.client.config_loader` has always been named `JacClientConfig`. There is no `PluginConfig` at that path. This causes an `ImportError` every time and is the direct cause of the warning the user sees.

**Verified**: I checked the state of `config_loader.jac` at the exact commit of PR #4422 (the commit that introduced this code, `da57cd2f`) and at the refactoring commit PR #6390. The class has only ever been `JacClientConfig`.

---

## Bug 2 — Wrong call pattern: `load()` is an instance method, not a classmethod

```jac
config = PluginConfig.load(self.project_dir);
```

Even if Bug 1 were fixed, this would still fail. `JacClientConfig.load()` is an instance method — it takes `self` as its only argument. The correct usage is:

```jac
cfg = JacClientConfig(project_dir=self.project_dir);
config = cfg.load();
```

Calling `JacClientConfig.load(self.project_dir)` passes a `Path` object as `self`, which would raise a `TypeError` (Path has no `_config` attribute).

---

## Bug 3 — `routing` key is never present in the loaded config dict

Even if Bugs 1 and 2 were both fixed, `config.routing` (or `config.get('routing')`) would always return `None`/`{}`.

`JacClientConfig.load()` (in `impl/config_loader.impl.jac`) overrides the base `load()` and explicitly builds a `user_config` dict with only these keys:

```jac
user_config = {
    'api': ..., 'base_path': ..., 'vite': ..., 'ts': ...,
    'configs': ..., 'paths': ..., 'npm': ..., 'pwa': ..., 'package': ...
}
```

`routing` is never included, even though `client_config = jac_config.get_plugin_config('client')` would have it if the user set `[plugins.client.routing]` in `jac.toml`. The key is read from the toml file but then silently dropped.

---

## History / Root Cause

The bug was introduced in **PR #4422** which first added file-based routing. The original `except` block was completely silent (`except Exception { }`), so the failure was invisible.

At some point after #4422, the except block was updated to emit `console.warning(...)`, which revealed the hidden failure. PR #6390 then moved the code into core and changed the import path from a relative `..config_loader` to the absolute `jaclang.runtimelib.client.config_loader` — but still with the wrong class name. The refactoring did not introduce the bug; it only moved it and made it visible.

**The `auth_redirect` configuration key has never worked since file-based routing was first shipped.**

---

## How to Reproduce

1. Create any jac project with file-based routing (a `pages/` directory containing at least one `.jac` file that exports `page`).
2. Run the project with `jac run main.jac` or build it.
3. Observe the warning in the terminal output:

```
⚠ Failed to load routing config, using default auth_redirect='/login': cannot import name 'PluginConfig' from 'jaclang.runtimelib.client.config_loader' (...)
```

The warning appears on every build regardless of what is in `jac.toml`.

---

## Impact

| Symptom | Severity |
|---|---|
| Warning printed to terminal on every run | Low (cosmetic, but noisy) |
| `auth_redirect` in `jac.toml` has no effect | Medium — unauthenticated users always redirect to `/login` with no way to change it |
| App functionality | Not affected — the `except` fallback keeps `auth_redirect = "/login"` and the build continues normally |

---

## References

- PR #4422 (introduced file-based routing)
- PR #6390 (moved code to core)
- Broken code: `jac/jaclang/runtimelib/client/impl/compiler.impl.jac` ~line 133
- Config loader class: `jac/jaclang/runtimelib/client/config_loader.jac`
- Config loader impl: `jac/jaclang/runtimelib/client/impl/config_loader.impl.jac`

**Comment by SahanUday** [comment]
## Bug 4 — Wrong `AuthGuard` call convention in generated `_entry.js`

Even after Bugs 1–3 are fixed, `auth_redirect` is correctly read from `jac.toml` and written into `_entry.js`, but the redirect **still does not take effect** at runtime.

**File:** `jac/jaclang/runtimelib/react_entry.jac` — `build_pages_react_entry_script()`, line ~104

### Root cause

PR #3736 changed how the Jac compiler compiles JSX-returning functions. Any function annotated `-> JsxElement` with named parameters now compiles to a React props-destructuring ABI:

```js
// What client_runtime.js currently contains (since PR #3736):
function AuthGuard(props) {
    const { redirect: redirect = "/login" } = props;
    ...
}
```

`react_entry.jac` was written before this change and still generates:

```js
function _AuthGuardRoute() { return AuthGuard("/dashboard"); }
```

When `AuthGuard("/dashboard")` is called, the string `"/dashboard"` becomes `props`. Inside `AuthGuard`, `props.redirect` is `undefined` on a string, so it falls back to the default `"/login"`. The configured value is silently discarded.

PR #6494 (Jun 2026) fixed the same mismatch for `.cl.jac` call sites, but `react_entry.jac` is Python-side string generation — not `.cl.jac` code — so it was missed.

### Fix

In `jac/jaclang/runtimelib/react_entry.jac`, replace the wrapper function with a direct `React.createElement` call that passes a proper props object:

```js
// Before (broken):
function _AuthGuardRoute() { return AuthGuard("/dashboard"); }
const authGuardElement = React.createElement(_AuthGuardRoute, null);

// After (fixed):
const authGuardElement = React.createElement(AuthGuard, { redirect: "/dashboard" });
```

`React.createElement(AuthGuard, { redirect: "/dashboard" })` passes `{ redirect: "/dashboard" }` as `props`, so `props.redirect = "/dashboard"` ✓

---
